"""Run caps: per session, with a global backstop.

Why not the daily cap per person: there is no login, so there is no identity.
The next best thing is a session id generated by the browser and sent as a
header. The backend counts per that id, so each visitor gets their own budget
and one visitor cannot spend everyone else's.

Two honest limitations:

1. The session id lives in `sessionStorage`, which anyone can clear. That makes
   it trivial to bypass, so it is abuse *deterrence*, not a security control.
   For a portfolio demo that is the right trade: it stops accidental overuse
   without pretending to stop a motivated actor.
2. Because of (1), a global ceiling still exists. If a visitor mints fresh ids,
   the global cap is what protects the Gemini free tier.

Counts live in the same in-memory SQLite as the tickets, so both caps reset on
backend restart as well as at midnight.
"""

from __future__ import annotations

import logging
import os
import re

from . import db

logger = logging.getLogger(__name__)

# Per visitor, per day.
DAILY_LIMIT = int(os.getenv("DAILY_RUN_LIMIT", "3"))

# Ceiling for the whole demo, across all sessions. Protects the free tier when
# someone mints new session ids.
GLOBAL_DAILY_LIMIT = int(os.getenv("DAILY_GLOBAL_LIMIT", "50"))

# sessionStorage values are untrusted input.
SESSION_ID_PATTERN = re.compile(r"^[A-Za-z0-9_-]{8,64}$")

FALLBACK_SESSION = "no-session"


class RateLimitError(Exception):
    """Raised when the caller has no executions left."""

    def __init__(self, used: int, limit: int, scope: str) -> None:
        super().__init__(f"Límite alcanzado en {scope}: {used}/{limit}")
        self.used = used
        self.limit = limit
        self.scope = scope


def sanitize_session_id(raw: str | None) -> str:
    """Validate a client-supplied session id.

    A missing or malformed id falls back to a shared bucket, which is
    intentionally stricter: a caller that cannot identify itself should not get
    a fresh budget on every request.
    """
    if not raw or not SESSION_ID_PATTERN.fullmatch(raw):
        return FALLBACK_SESSION
    return raw


def _count(conn, bucket: str) -> int:
    row = conn.execute(
        "SELECT COUNT(*) AS n FROM runs "
        "WHERE user_id = ? AND date(run_at) = date('now')",
        (bucket,),
    ).fetchone()
    return int(row["n"] if row else 0)


def _count_all(conn) -> int:
    """Every run today, whatever session it belonged to."""
    row = conn.execute(
        "SELECT COUNT(*) AS n FROM runs WHERE date(run_at) = date('now')"
    ).fetchone()
    return int(row["n"] if row else 0)


def used_today(session_id: str | None = None) -> int:
    """Executions used by one session today."""
    conn = db.get_connection()
    with db._LOCK:
        return _count(conn, sanitize_session_id(session_id))


def used_global() -> int:
    """Executions used by the whole demo today, across all sessions."""
    conn = db.get_connection()
    with db._LOCK:
        return _count_all(conn)


def remaining_today(session_id: str | None = None) -> int:
    return max(DAILY_LIMIT - used_today(session_id), 0)


def record_run(status: str, session_id: str | None = None) -> None:
    """Insert a run row. Used by tests."""
    conn = db.get_connection()
    with db._LOCK:
        conn.execute(
            "INSERT INTO runs (user_id, status) VALUES (?, ?)",
            (sanitize_session_id(session_id), status),
        )
        conn.commit()


def mark_finished(status: str, session_id: str | None = None) -> None:
    """Stamp the outcome onto the row that `consume` already inserted.

    Exactly one row per execution, otherwise the count doubles and the real cap
    is half of what it says.
    """
    bucket = sanitize_session_id(session_id)
    conn = db.get_connection()
    with db._LOCK:
        conn.execute(
            "UPDATE runs SET status = ? "
            "WHERE id = (SELECT id FROM runs "
            "            WHERE user_id = ? AND status = 'started' "
            "            ORDER BY id DESC LIMIT 1)",
            (status, bucket),
        )
        conn.commit()


def consume(session_id: str | None = None) -> None:
    """Atomically check both caps and count one execution.

    Check and insert share the same lock, so two simultaneous requests cannot
    both slip past the last remaining slot.
    """
    bucket = sanitize_session_id(session_id)
    conn = db.get_connection()
    with db._LOCK:
        used = _count(conn, bucket)
        if used >= DAILY_LIMIT:
            logger.info("Límite por sesión alcanzado (%s/%s)", used, DAILY_LIMIT)
            raise RateLimitError(used, DAILY_LIMIT, "sesión")

        used_global = _count_all(conn)
        if used_global >= GLOBAL_DAILY_LIMIT:
            logger.info(
                "Techo global alcanzado (%s/%s)", used_global, GLOBAL_DAILY_LIMIT
            )
            raise RateLimitError(used_global, GLOBAL_DAILY_LIMIT, "demo")

        conn.execute(
            "INSERT INTO runs (user_id, status) VALUES (?, 'started')",
            (bucket,),
        )
        conn.commit()


# Kept for callers that only need the check.
check_and_consume = consume
